# Exported from Render on 2025-05-11T09:19:25Z
services:
- type: web
  name: TaskManager
  runtime: docker
  repo: https://github.com/manojshendge/TaskManager
  plan: free
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
